# use-grammars = { only = [ "less" ] }

[language-server.copilot]
command = "copilot"
args = ["--stdio"]

[language-server.gpt]
command = "/home/cem/Setups/helix-gpt-run.sh"
# args = ["--logFile", "/home/cem/.cache/helix/gpt.log"]

[language-server.ollama]
command = "/home/cem/Setups/helix-ollama-run.sh"
# args = ["--logFile", "/home/cem/.cache/helix/gpt.log"]

# [language-server.lsp-ollama]
# command = "bun"
# args = ["run", "/home/cem/Setups/lsp-ollama/src/index.ts", "--stdio"]
# [[language]]
# name = "*"
# language-servers = [ "copilot"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "gpt"]

[[language]]
name = "python"
language-servers = [ "pylsp", "gpt" ]

[[language]]
name = "c"
language-servers = [ "gpt" ]
# language-servers = [ "clangd", "gpt" ]
# file-types = ["c"] # TODO: ["h"]
file-types = ["c", "h"]

[[language]]
name = "javascript"
# language-servers = [ "typescript-language-server", "gpt" ]
language-servers = [ "typescript-language-server", "gpt" ]

[[language]]
name = "typescript"
# language-servers = [ "typescript-language-server", "gpt" ]
language-servers = [ "typescript-language-server", "gpt" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "gpt" ]

[[language]]
name = "html"
auto-format = false
language-servers = [ "vscode-html-language-server", "gpt" ]

[[language]]
name = "bash"
language-servers = [ "bash-language-server" , "gpt" ]

[[language]]
name = "svelte"
# language-servers = [ "gpt" ]
language-servers = [ "svelteserver", "gpt" ]
file-types = [ "svelte" ]

[[language]]
name = "perl"
file-types = ["pl", "pm"]
language-servers = [ "gpt", "perlnavigator" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "gpt" ]

# [[language]]
# name = "less"
# scope = "source.less"
# injection-regex = "less"
# file-types = ["less"]
# roots = []
# language-servers = [ "vscode-css-language-server" ]
# auto-format = false
# indent = { tab-width = 2, unit = "  " }

# [[grammar]]
# name = "less"
# source = { git = "https://github.com/rhino1998/tree-sitter-less", rev = "2bd739e106a3485bca210cf7b6d25ba09fd10dff" }

[[language]]
name = "scss"
file-types = ["scss", "less"]
auto-format = false
language-servers = [ "gpt" ]
